tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - sbt test
  except:
  - master@seng302-2019/team-800  # do not run on master as jacoco runs tests itself
  artifacts:
    when: on_failure
    name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}_FAILED"
    paths:
    - "."
    untracked: false
    expire_in: 1 day

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags

update-sonar:
    stage: deploy
    script:
        - sbt jacoco
        - /home/sengstudent/sonarqubeScanner/bin/sonar-scanner --debug
#    only:
#        - master@seng302-2019/team-800