tag_checker:
  stage: build
  script:
  - python tag_checker.py $CI_COMMIT_TAG
  only:
  - tags

junit:
  stage: test
  script:
  - python envCreator.py $GOOGLE_MAPS_API_KEY $EVENTFINDA_API_KEY_USERNAME $EVENTFINDA_API_KEY_PASSWORD $ADMIN_USER_PASSWORD_DEFAULT $TEST_USER_PASSWORD_DEFAULT
  - sbt test
  except:
  - master@seng302-2019/team-800  # do not run on master as jacoco runs tests itself
  artifacts:
    when: on_failure
    name: "${CI_BUILD_STAGE}_${CI_BUILD_REF_NAME}_FAILED"
    paths:
    - "."
    untracked: false
    expire_in: 1 day

recent-artifacts:
  stage: deploy
  script:
  - sbt dist
  artifacts:
    paths:
    - target/universal/*.zip
    expire_in: 1 week
  except:
  - tags

release-artifacts:
  stage: deploy
  script:
  - sbt dist
  artifacts:
    paths:
    - target/universal/*.zip
  only:
  - tags

update-sonar:
  stage: deploy
  script:
  - python envCreator.py $GOOGLE_MAPS_API_KEY $EVENTFINDA_API_KEY_USERNAME $EVENTFINDA_API_KEY_PASSWORD $ADMIN_USER_PASSWORD_DEFAULT $TEST_USER_PASSWORD_DEFAULT
  - sbt jacoco
  - /opt/sonar-scanner/bin/sonar-scanner --debug
  only:
  - master@seng302-2019/team-800